server:
  port: 8080
fixedDelay: 5000
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: testtock
          contentType: text/plain
          binder: rabbit1
      binders:
         rabbit1:
            type: rabbit
            environment:
              spring:
                rabbitmq:
                  host: 10.5.16.14   #rabbitMQ服务器地址
                  port: 5672          #rabbitMQ服务器端口
