spring:
  cloud:
    stream:
      bindings:
        input: testtock
	    binder: rabbit1
	  binders:
	    rabbit1:
	      type: rabbit
	      environment:
	        spring:
	          rabbitmq:
	            host: 10.5.16.14   #rabbitMQ服务器地址
	            port: 5672          #rabbitMQ服务器端口